export const EXERCISES = [
  "Squats",
  "Back Squats",
  "Front Squats",
  "Hack Squats",
  "Bulgarian Split Squats",
  "Jump Squats",
  "Box Squats",
  "Goblet Squats",
  "Overhead Squats",
  "Pause Squats",
  "Zercher Squats",
  "Deadlifts",
  "Romanian Deadlifts",
  "Sumo Deadlifts",
  "Deficit Deadlifts",
  "Stiff-Leg Deadlifts",
  "Single-Leg Deadlifts",
  "Rack Pulls",
  "Bench Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Close-Grip Bench Press",
  "Dumbbell Bench Press",
  "Floor Press",
  "Push-Ups",
  "Diamond Push-Ups",
  "Wide-Grip Push-Ups",
  "Decline Push-Ups",
  "Incline Push-Ups",
  "Plyometric Push-Ups",
  "Military Press",
  "Seated Dumbbell Press",
  "Standing Overhead Press",
  "Arnold Press",
  "Push Press",
  "Behind-the-Neck Press",
  "Viking Press",
  "Lateral Raises",
  "Front Raises",
  "Bent-Over Lateral Raises",
  "Cable Lateral Raises",
  "Plate Raises",
  "Pull-Ups",
  "Chin-Ups",
  "Wide-Grip Pull-Ups",
  "Close-Grip Pull-Ups",
  "Neutral-Grip Pull-Ups",
  "Assisted Pull-Ups",
  "Band-Assisted Pull-Ups",
  "Lat Pulldowns",
  "Wide-Grip Lat Pulldowns",
  "Close-Grip Lat Pulldowns",
  "Behind-the-Neck Pulldowns",
  "Straight-Arm Pulldowns",
  "Rows",
  "Barbell Rows",
  "Pendlay Rows",
  "T-Bar Rows",
  "Seated Cable Rows",
  "Single-Arm Dumbbell Rows",
  "Meadows Rows",
  "Inverted Rows",
  "Face Pulls",
  "Upright Rows",
  "Yates Rows",
  "Bent-Over Rows",
  "Machine Rows",
  "Chest-Supported Rows",
  "Dumbbell Curls",
  "Barbell Curls",
  "Preacher Curls",
  "Hammer Curls",
  "Concentration Curls",
  "Spider Curls",
  "Zottman Curls",
  "Reverse Curls",
  "Cable Curls",
  "21s Curls",
  "Tricep Extensions",
  "Skull Crushers",
  "Overhead Tricep Extensions",
  "Cable Pushdowns",
  "Rope Pushdowns",
  "Diamond Push-Ups",
  "Close-Grip Bench Press",
  "French Press",
  "Tricep Kickbacks",
  "JM Press",
  "Dips",
  "Chest Dips",
  "Tricep Dips",
  "Assisted Dips",
  "Weighted Dips",
  "Parallel Bar Dips",
  "Ring Dips",
  "Leg Press",
  "Hack Press",
  "V-Squat",
  "Calf Raises",
  "Standing Calf Raises",
  "Seated Calf Raises",
  "Donkey Calf Raises",
  "Smith Machine Calf Raises",
  "Leg Extensions",
  "Leg Curls",
  "Seated Leg Curls",
  "Lying Leg Curls",
  "Standing Leg Curls",
  "Nordic Curls",
  "Good Mornings",
  "Seated Good Mornings",
  "Hip Thrusts",
  "Glute Bridges",
  "Single-Leg Hip Thrusts",
  "Cable Hip Thrusts",
  "Lunges",
  "Walking Lunges",
  "Reverse Lunges",
  "Side Lunges",
  "Jump Lunges",
  "Curtsy Lunges",
  "Step-Ups",
  "Box Step-Ups",
  "Lateral Step-Ups",
  "Weighted Step-Ups",
  "Shrugs",
  "Barbell Shrugs",
  "Dumbbell Shrugs",
  "Behind-the-Back Shrugs",
  "Smith Machine Shrugs",
  "Cable Shrugs",
  "Crunches",
  "Reverse Crunches",
  "Bicycle Crunches",
  "Cable Crunches",
  "Decline Crunches",
  "Russian Twists",
  "Medicine Ball Russian Twists",
  "Planks",
  "Side Planks",
  "Plank Reaches",
  "Dynamic Planks",
  "RKC Planks",
  "Ab Wheel Rollouts",
  "Standing Ab Wheel Rollouts",
  "Hanging Leg Raises",
  "Lying Leg Raises",
  "Captain's Chair Leg Raises",
  "Dragon Flags",
  "Windshield Wipers",
  "Cable Woodchops",
  "Medicine Ball Slams",
  "Turkish Get-Ups",
  "Farmer's Walks",
  "Suitcase Carries",
  "Overhead Carries",
  "Rack Carries",
  "Yoke Walks",
  "Clean",
  "Power Clean",
  "Hang Clean",
  "Clean and Press",
  "Clean and Jerk",
  "Snatch",
  "Power Snatch",
  "Hang Snatch",
  "Muscle Snatch",
  "High Pulls",
  "Upright Rows",
  "Behind-the-Neck Press",
  "Push Press",
  "Split Jerk",
  "Power Jerk",
  "Squat Jerk",
  "Kettlebell Swings",
  "Russian Kettlebell Swings",
  "American Kettlebell Swings",
  "Single-Arm Kettlebell Swings",
  "Kettlebell Clean and Press",
  "Kettlebell Snatch",
  "Goblet Squats",
  "Wrist Curls",
  "Reverse Wrist Curls",
  "Plate Pinches",
  "Dead Hangs",
  "Towel Pull-Ups",
  "Grip Crushers",
  "Plate Curls",
  "Band Pull-Aparts",
  "External Rotations",
  "Internal Rotations",
  "Wall Slides",
  "Scapular Pull-Ups",
  "Band Dislocates",
  "YTWLs",
  "Prone Y Raises",
  "Prone T Raises",
  "Prone W Raises",
  "Prone L Raises",
  "Shoulder Taps",
  "Pike Push-Ups",
  "Handstand Push-Ups",
  "Wall Walks",
  "Bear Crawls",
  "Crab Walks",
  "Inchworm Walks",
  "Mountain Climbers",
  "Spider-Man Climbers",
  "Burpees",
  "Box Jumps",
  "Depth Jumps",
  "Broad Jumps",
  "Vertical Jumps",
  "Scissor",
  "Plyo Push-Ups",
  "Medicine Ball Chest Throws",
  "Medicine Ball Rotational Throws",
  "Battle Rope Waves",
  "Battle Rope Slams",
  "Rope Climbs",
  "Sled Pushes",
  "Sled Pulls",
  "Prowler Pushes",
  "Tire Flips",
  "Sledgehammer Strikes",
  "Box Squats",
  "Anderson Squats",
  "Sissy Squats",
  "Belt Squats",
  "Safety Bar Squats",
  "Cambered Bar Squats",
  "Hindu Squats",
  "Pistol Squats",
  "Shrimp Squats",
  "Dragon Squats",
  "Jefferson Deadlifts",
  "Reeves Deadlifts",
  "Snatch Grip Deadlifts",
  "Axle Deadlifts",
  "Block Pulls",
  "Band Deadlifts",
  "Chain Deadlifts",
  "Good Mornings",
  "Seated Good Mornings",
  "Banded Good Mornings",
  "Back Extensions",
  "Reverse Hyperextensions",
  "GHD Raises",
  "Nordic Hamstring Curls",
  "Glute-Ham Raises",
  "Superman Holds",
  "Bird Dogs",
  "Cat-Cow Stretches",
  "Scorpion Stretches",
  "Thread the Needle",
  "Child's Pose",
  "Downward Dog",
  "Cobra Stretches",
  "McKenzie Press-Ups",
  "Jefferson Curls",
  "Resistance Band Pull-Aparts",
  "Band Face Pulls",
  "Band No Money",
  "Chest Flyes",
  "Dumbbell Flyes",
  "Cable Flyes",
  "Pec Deck",
  "Decline Flyes",
  "Incline Flyes",
  "Standing Cable Flyes",
  "Low to High Cable Flyes",
  "High to Low Cable Flyes",
  "Crossover Flyes",
  "Plate Squeeze Press",
  "Svend Press",
  "Band Resisted Push-Ups",
  "Dumbbell Pull-Overs",
  "Straight Arm Pulldowns",
  "Cable Pull-Overs",
  "Meadows Rows",
  "Helms Rows",
  "Seal Rows",
  "Chest-Supported Rows",
  "Machine High Rows",
  "Low Cable Rows",
  "Seated Machine Rows",
  "One-Arm Cable Rows",
  "Barbell Corner Rows",
  "Charles Glass Rows",
  "Reverse Flyes",
  "Bent-Over Reverse Flyes",
  "Cable Reverse Flyes",
  "Machine Reverse Flyes",
  "Prone Reverse Flyes",
  "Incline Reverse Flyes",
  "Decline Reverse Flyes",
  "Face Pulls with External Rotation",
  "High Pulls",
  "Power High Pulls",
  "Band Pull-Aparts",
  "Prone Y Raises",
  "Rotator Cuff External Rotations",
  "Rotator Cuff Internal Rotations",
  "Cable External Rotations"
];